### PR TITLE
treat quote issues as warning

### PR DESCRIPTION
**Pull request by tobru**
this one drives me crazy...

### CODE REVIEW

**Comment by akosma** [comment]
What is this issue?

**Comment by tobru** [comment]
"blabla." vs "blabla".

**Comment by akosma** [comment]
Maybe it would be time to stop using vale altogether instead? I mean, there's a lot of backlash against it anyway.

**Comment by mhutter** [comment]
Or at least provide our own rules. I think it's a good thing to have an uniform writing style across all documents, but I struggle a lot with Vale because Microsoft's rule often conflict with what I learned as good writing style

**Comment by arska** [comment]
Just because keeping up a good writing style is a pain in the butt, especially for non-natives, is not a reason not to do it or use tooling that helps us do it. We have been customizing the error/warnings (https://github.com/vshn/vale/blob/eebc43faae7330b3740e0d35566fe0f4c826a7a1/vale.ini) and I have no objection to downgrading the Quotes to a warning.

**Comment by tobru** [comment]
Vale with the Microsoft style keeps getting in my way of writing. It didn't help me in the past and I had to rewrite stuff into a style which is neither mine nor did I like it. It doesn't bring _any_ value to me, it only makes writing a pain for me and I start writing less because of that. As an alternative I propose a "classic" spell checker, which we already have: https://github.com/vshn/hunspell. And remove vale from our documentation tooling.

**Pull request merged**
